blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name = 'home')
]

talktech/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from talktech.urls import auth_views

from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('adminer/', admin.site.urls),
    path('about/', views.about, name = 'about'),
    
    path('login', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)    

users/urls.py
from django.urls import path

from . import views

# USERS URLS

app_name = 'users'

urlpatterns = [
    path('register', views.register, name = 'register'),
    path('profile/', views.profile, name = 'profile'),
]

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# USERS MODELS

from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default = 'default.jpg', upload_to = 'profile_pics')

    def __str__(self):
        return "{} Profile".format(self.user.username)
    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

blog/views.py
from django.shortcuts import render

# BLOG VIEWS

def home(request):
    return render(request, 'blog/home.html')

contact/views.py
from django.shortcuts import render

# Create your views here.

talktech/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'pages/home.html')

def about(request):
    return render(request, 'pages/about.html')

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .forms import UserRegisterForm

# USERS VIEWS

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = form.cleaned_data.get('username')
            messages.success(request, f'{user_name}, your account has been created succefully! You can login now')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form':form})

@login_required
def profile(request):
    return render(request, 'users/profile.html')

blog/templates/blog/home.html
{% extends 'layouts/base.html' %}
{% block title %} talktech blog {% endblock title %}

{% block content %}
    <h1> Bienvenu sur notre blog </h1>
{% endblock content %}

templates/layouts/_footer.html
<div class="mt-4">
    <p> &copy; {% now "Y" %} &middot; talktech &middot; all rights reserved </p>
</div>

templates/layouts/_nav.html
<nav class="navbar navbar-expand-lg navbar-light top-nav-bar">
    <div class="container">
        <a class="navbar-brand logo" href="{% url 'home' %}">TalkTech</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Join</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/layouts/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <title>Parlons Talk Technologies</title>

        <!--============ Bootstrap files ============-->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

        <!--=============== Custom styles files ==============-->
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        
    </head>
    <body>
        <!--============ include nav bar template ============-->
        <header class="header">
            {% include 'layouts/_nav.html' %}
        </header>

        <div class = "container">
            <!--============ main content block ============-->
            <main class="main">
                <div class="">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}"> {{ message }} </div>
                        {% endfor %}
                    {% endif %}
                    {% block content %}{% endblock content %}
                <div>
            </main>

            <footer class="footer">
            <!--============ include footer template ============-->
                {% include "layouts/_footer.html" %}
            </footer>
        </div>
        <!--============ load script files ============-->
        <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!--============ load custom script files ============-->
        <script src="{% static 'js/app.js' %}"></script>
    </body>
</html>

templates/pages/about.html
{% extends "layouts/base.html" %}

{% block content %}
    <h1 class="display-1"> About </h1>
{% endblock content %}

templates/pages/home.html
{% extends "layouts/base.html" %}

{% block active %}active{% endblock active %}

{% block content %}
    <h1 class="">Talk Technologies Club</h1>
    <p class="">
        Based at UCBC campus, we share knolodge and experiences in technology.
        <br>We believe that technology changes the way we think, make better our lives and 
        the sharing is in the heart of it's revolution.
    </p>
    <p class="">
        <a href="{% url 'users:register' %}" class="btn btn-primary">Join now</a>
    </p>
{% endblock content %}

users/templates/users/login.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% block title %} login {% endblock title %}

{% block content %}
<div class="content-section container col-lg-6">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login Now</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Login</button>
        </div>
        <div class="border-top mt-3">
            <small class="text-muted">
                Need an account? <a href="{% url 'users:register' %}" class="ml-2">Sign Up Now</a>
            </small>
        </div>
    </form>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'layouts/base.html' %}
{% block title %} Logout {% endblock title %}

{% block content %}
<div class="content-section container col-lg-6">
    <h2> You have been loged out </h2>
    <div class="border-top mt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}" class="ml-2">Login again</a>
        </small>
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "layouts/base.html" %},
{% block title %} {{ user.username }} Profile {% endblock title %}

{% block content %}
    <div class="media">
        <img src="{{ user.profile.image.url }}" alt="user profile image" class="rounded-circle account-img" width="60px">
        <div class="media-body ml-3">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary"> {{ user.email }}</p>
        </div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% comment %} <form action="" method="POST" class="">
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <button type="submit" class="btn btn-danger"> Submit </button>
    </p>
</form> {% endcomment %}

<div class="content-section container col-lg-6">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Sign Up</button>
        </div>
        <div class="border-top mt-3">
            <small class="text-muted">
                Already have an account? <a href="#" class="ml-2">Sign In</a>
            </small>
        </div>
    </form>
</div>
{% endblock content %}